version: "3"
services:
    wordpress:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./WorkSpaceJKPG:/var/www/html
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        restart: always
        ports: 
            - "3306:3306"
        volumes:
            - ./SeedSQL:/docker-entrypoint-initdb.d
            - WorkSpaceJKPG_DB_Data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db
        ports:
            - 8000:80
        networks:
            - default
volumes:
    WorkSpaceJKPG_DB_Data:
