version: '2' # version of docker-compose to use
services: # configuring each container
    db: # name of our mysql container
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment: # environment variables -- mysql options in this case
            MYSQL_DATABASE: wp
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/db_WorkSpaceJKPG
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:mysql
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    wordpress:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./WorkSpaceJKPG:/var/www/html/
        links:
            - db:mysql
        networks:
            - default
volumes:
    db_data_WorkSpaceJKPG: